
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS clans(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,captain_id INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS members(clan_id INTEGER NOT NULL,user_id INTEGER UNIQUE NOT NULL,joined_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(clan_id,user_id));
CREATE TABLE IF NOT EXISTS invites(id INTEGER PRIMARY KEY AUTOINCREMENT,clan_id INTEGER NOT NULL,inviter_id INTEGER NOT NULL,invitee_id INTEGER NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS challenges(id INTEGER PRIMARY KEY AUTOINCREMENT,creator_clan_id INTEGER NOT NULL,accepter_clan_id INTEGER,status TEXT DEFAULT 'open',map1 TEXT NOT NULL,map2 TEXT NOT NULL,map3 TEXT NOT NULL,winner_clan_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,completed_at TEXT);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,challenge_id INTEGER NOT NULL,clan_id INTEGER NOT NULL,winner_clan_id INTEGER NOT NULL,UNIQUE(challenge_id,clan_id));
CREATE TABLE IF NOT EXISTS scores(clan_id INTEGER PRIMARY KEY,points INTEGER DEFAULT 0,wins INTEGER DEFAULT 0,losses INTEGER DEFAULT 0,played INTEGER DEFAULT 0);
