
const MAPS=["Slums","Standoff","Yemen","Express","Raid","Plaza"],COOKIE="bol_session";
const J=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json",...h}});
const b=async r=>{try{return await r.json()}catch{return {}}};
const cv=(r,n)=>{let m=(r.headers.get("Cookie")||"").match(new RegExp("(^|;\\s*)"+n+"=([^;]+)"));return m?decodeURIComponent(m[2]):null};
const ck=v=>`${COOKIE}=${encodeURIComponent(v)}; Path=/; Max-Age=604800; HttpOnly; SameSite=Lax; Secure`;
async function hp(p,s){let e=new TextEncoder(),k=await crypto.subtle.importKey("raw",e.encode(p),"PBKDF2",false,["deriveBits"]),x=await crypto.subtle.deriveBits({name:"PBKDF2",salt:e.encode(s),iterations:120000,hash:"SHA-256"},k,256);return btoa(String.fromCharCode(...new Uint8Array(x))).replaceAll("=","")}
async function hash(p){let s=crypto.randomUUID();return s+"."+await hp(p,s)}
async function verify(p,v){let [s,h]=v.split(".");return await hp(p,s)===h}
async function user(r,e){let t=cv(r,COOKIE);if(!t)return null;let x=await e.DB.prepare("SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?").bind(t,Date.now()).first();return x||null}
async function clan(e,id){return e.DB.prepare("SELECT c.* FROM clans c JOIN members m ON m.clan_id=c.id WHERE m.user_id=?").bind(id).first()}
function maps(){return [...MAPS].sort(()=>Math.random()-.5).slice(0,3)}
async function api(r,e,p){
 let u=await user(r,e),x=()=>b(r);
 if(r.method==="GET"&&p==="/api/me")return J({user:u,clan:u?await clan(e,u.id):null});
 if(r.method==="POST"&&p==="/api/register"){let z=await x(),n=(z.username||"").trim(),pw=z.password||"";if(n.length<3||n.length>20||pw.length<6)return J({error:"Usuario 3-20 caracteres y contraseña de 6 o más."},400);if(await e.DB.prepare("SELECT id FROM users WHERE username=?").bind(n).first())return J({error:"Ese usuario ya existe."},400);let q=await e.DB.prepare("INSERT INTO users(username,password_hash) VALUES(?,?)").bind(n,await hash(pw)).run(),t=crypto.randomUUID();await e.DB.prepare("INSERT INTO sessions VALUES(?,?,?)").bind(t,q.meta.last_row_id,Date.now()+6048e5).run();return J({ok:true,user:{id:q.meta.last_row_id,username:n}},200,{"Set-Cookie":ck(t)})}
 if(r.method==="POST"&&p==="/api/login"){let z=await x(),q=await e.DB.prepare("SELECT * FROM users WHERE username=?").bind((z.username||"").trim()).first();if(!q||!(await verify(z.password||"",q.password_hash)))return J({error:"Usuario o contraseña incorrectos."},401);let t=crypto.randomUUID();await e.DB.prepare("INSERT INTO sessions VALUES(?,?,?)").bind(t,q.id,Date.now()+6048e5).run();return J({ok:true},200,{"Set-Cookie":ck(t)})}
 if(r.method==="POST"&&p==="/api/logout")return J({ok:true},200,{"Set-Cookie":`${COOKIE}=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax; Secure`});
 if(!u)return J({error:"Debes iniciar sesión."},401);
 if(r.method==="GET"&&p==="/api/invites")return J((await e.DB.prepare("SELECT i.id,c.name clan FROM invites i JOIN clans c ON c.id=i.clan_id WHERE i.invitee_id=? AND i.status='pending'").bind(u.id).all()).results);
 if(r.method==="POST"&&p==="/api/clans"){if(await clan(e,u.id))return J({error:"Ya perteneces a un clan."},400);let z=await x(),n=(z.name||"").trim();if(n.length<2||n.length>24)return J({error:"Nombre de clan: 2-24 caracteres."},400);try{let q=await e.DB.prepare("INSERT INTO clans(name,captain_id) VALUES(?,?)").bind(n,u.id).run();await e.DB.batch([e.DB.prepare("INSERT INTO members VALUES(?,?,CURRENT_TIMESTAMP)").bind(q.meta.last_row_id,u.id),e.DB.prepare("INSERT INTO scores(clan_id) VALUES(?)").bind(q.meta.last_row_id)]);return J({ok:true})}catch{return J({error:"Ese clan ya existe."},400)}}
 if(r.method==="GET"&&p==="/api/clan"){let c=await clan(e,u.id);if(!c)return J({clan:null});let m=await e.DB.prepare("SELECT u.id,u.username,(u.id=? ) captain FROM users u JOIN members m ON m.user_id=u.id WHERE m.clan_id=?").bind(c.captain_id,c.id).all(),s=await e.DB.prepare("SELECT * FROM scores WHERE clan_id=?").bind(c.id).first();return J({clan:c,members:m.results,score:s})}
 if(r.method==="POST"&&p==="/api/clan/invite"){let c=await clan(e,u.id);if(!c||c.captain_id!==u.id)return J({error:"Solo el capitán puede invitar."},403);let n=await e.DB.prepare("SELECT COUNT(*) n FROM members WHERE clan_id=?").bind(c.id).first();if(n.n>=8)return J({error:"El clan ya tiene 8 jugadores."},400);let z=await x(),v=await e.DB.prepare("SELECT id FROM users WHERE username=?").bind((z.username||"").trim()).first();if(!v)return J({error:"Jugador no encontrado."},404);if(await clan(e,v.id))return J({error:"Ese jugador ya tiene clan."},400);await e.DB.prepare("INSERT INTO invites(clan_id,inviter_id,invitee_id) VALUES(?,?,?)").bind(c.id,u.id,v.id).run();return J({ok:true})}
 let im=p.match(/^\/api\/invites\/(\d+)\/accept$/);if(r.method==="POST"&&im){let q=await e.DB.prepare("SELECT * FROM invites WHERE id=? AND invitee_id=? AND status='pending'").bind(im[1],u.id).first();if(!q)return J({error:"Invitación no encontrada."},404);if(await clan(e,u.id))return J({error:"Ya tienes clan."},400);await e.DB.batch([e.DB.prepare("INSERT INTO members VALUES(?,?,CURRENT_TIMESTAMP)").bind(q.clan_id,u.id),e.DB.prepare("UPDATE invites SET status='accepted' WHERE id=?").bind(q.id)]);return J({ok:true})}
 if(r.method==="GET"&&p==="/api/leaderboard")return J((await e.DB.prepare("SELECT c.id,c.name,s.points,s.wins,s.losses,s.played FROM clans c LEFT JOIN scores s ON s.clan_id=c.id ORDER BY COALESCE(s.points,0) DESC,COALESCE(s.wins,0) DESC").all()).results);
 if(r.method==="POST"&&p==="/api/challenges"){let c=await clan(e,u.id);if(!c||c.captain_id!==u.id)return J({error:"Solo el capitán puede crear retos."},403);let m=maps(),q=await e.DB.prepare("INSERT INTO challenges(creator_clan_id,accepter_clan_id,map1,map2,map3) VALUES(?,NULL,?,?,?)").bind(c.id,...m).run();return J({ok:true,id:q.meta.last_row_id})}
 if(r.method==="GET"&&p==="/api/challenges"){let c=await clan(e,u.id),id=c?.id||-1,q=await e.DB.prepare("SELECT ch.*,a.name creator_name,b.name accepter_name FROM challenges ch JOIN clans a ON a.id=ch.creator_clan_id LEFT JOIN clans b ON b.id=ch.accepter_clan_id WHERE ch.status='open' OR ch.creator_clan_id=? OR ch.accepter_clan_id=? ORDER BY ch.id DESC").bind(id,id).all();return J(q.results.map(v=>({...v,creator_name:v.status==="open"?null:v.creator_name,maps:v.status==="open"?[]:[v.map1,v.map2,v.map3],mine:v.creator_clan_id===id||v.accepter_clan_id===id})))}
 let ca=p.match(/^\/api\/challenges\/(\d+)\/accept$/);if(r.method==="POST"&&ca){let c=await clan(e,u.id);if(!c||c.captain_id!==u.id)return J({error:"Solo el capitán puede aceptar."},403);let q=await e.DB.prepare("SELECT * FROM challenges WHERE id=? AND status='open'").bind(ca[1]).first();if(!q||q.creator_clan_id===c.id)return J({error:"Reto no disponible."},400);await e.DB.prepare("UPDATE challenges SET accepter_clan_id=?,status='accepted' WHERE id=?").bind(c.id,q.id).run();return J({ok:true})}
 let cr=p.match(/^\/api\/challenges\/(\d+)\/report$/);if(r.method==="POST"&&cr){let c=await clan(e,u.id);if(!c||c.captain_id!==u.id)return J({error:"Solo el capitán puede reportar."},403);let z=await x(),q=await e.DB.prepare("SELECT * FROM challenges WHERE id=? AND status='accepted'").bind(cr[1]).first();if(!q||![q.creator_clan_id,q.accepter_clan_id].includes(c.id))return J({error:"Reto no encontrado."},404);let w=+z.winner_clan_id;await e.DB.prepare("INSERT OR REPLACE INTO reports(challenge_id,clan_id,winner_clan_id) VALUES(?,?,?)").bind(q.id,c.id,w).run();let rs=(await e.DB.prepare("SELECT * FROM reports WHERE challenge_id=?").bind(q.id).all()).results;if(rs.length===2&&rs[0].winner_clan_id===rs[1].winner_clan_id){let l=w===q.creator_clan_id?q.accepter_clan_id:q.creator_clan_id;await e.DB.batch([e.DB.prepare("UPDATE challenges SET status='completed',winner_clan_id=?,completed_at=CURRENT_TIMESTAMP WHERE id=?").bind(w,q.id),e.DB.prepare("UPDATE scores SET points=points+20,wins=wins+1,played=played+1 WHERE clan_id=?").bind(w),e.DB.prepare("UPDATE scores SET points=points+5,losses=losses+1,played=played+1 WHERE clan_id=?").bind(l)]);return J({ok:true,completed:true})}return J({ok:true,message:"Resultado enviado; falta confirmar al otro capitán."})}
 return J({error:"No encontrado."},404)
}
export default{async fetch(r,e){let u=new URL(r.url);return u.pathname.startsWith("/api/")?api(r,e,u.pathname):e.ASSETS.fetch(r)}};
